model:
  model_path_hf: "microsoft/deberta-v3-base"
  output_model_path: "deberta3base_512"

data:
  train_dataset_path: "./train.json"

max_length: 512

output_dir: "test_trainer_log"

training:
  learning_rate: 2e-5
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 2
  report_to: "tensorboard"
  evaluation_strategy: "no"
  do_eval: False
  save_total_limit: 1
  logging_steps: 20
  lr_scheduler_type: "cosine"
  metric_for_best_model: "f1"
  greater_is_better: True
  warmup_ratio: 0.1
  weight_decay: 0.01

mlflow:
  exp_name: "finetune_deberta"
  run_name: "run_1"